### ISSUE TITLE
Change deployment strategy to Recreate

### ISSUE THREAD

**Issue by jorgemoralespou** [sonatype/docker-rhel-nexus#6]
When using persistent storage, and if the storage is not RWMany, there can be issues, so it's safer to change Rolling to Recreate as redeployment strategy. Even though it will incur in a little downtime, it's safer.

https://github.com/jorgemoralespou/nexus-ose/blob/master/nexus/ose3/nexus3-resources.json#L148-L166

**Comment by whyjustin** [comment]
Fixed in #10.
