### ISSUE TITLE
No liveness checks

### ISSUE THREAD

**Issue by garethahealy** [sonatype/docker-rhel-nexus#8]
Has a readiness but no liveness

https://github.com/sonatype/docker-rhel-nexus/blob/master/OpenShift/nexus3.json#L214

**Comment by whyjustin** [comment]
Liveness Probe added 840f3d76b52f7646721bc0cbc339c69d54e6f883. Readiness probe is abused currently as from the Kubernetes docs it should determine whether the server is live but not ready for traffic (which It currently doesn't). Either way I believe this issue is fixed.
