### ISSUE TITLE
Readiness check fails due to 401

### ISSUE THREAD

**Issue by garethahealy** [sonatype/docker-rhel-nexus#9]
Access to /service/metrics/ping requires basic auth. As the readiness prob doesn't pass this, it fails.

Might be good to move to a bash script like: 

https://github.com/jorgemoralespou/nexus-ose/blob/master/nexus/nexus3-container/usr/local/bin/readinessProbe.sh

**Comment by whyjustin** [comment]
Fixed via https://github.com/sonatype/docker-rhel-nexus/pull/22
